name: KiBot

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  kibot:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto_full:latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Replace .stpZ with .step in PCB file
        run: |
          find . -name "*.kicad_pcb" -type f -exec sed -i 's/\.stpZ/.step/g' {} \;

      - name: Run KiBot
        run: |
         cd ${GITHUB_WORKSPACE}/hw/creeper/ && kibot -d ${GITHUB_WORKSPACE}/kibot_outputs -c creeper.kibot.yaml
         touch ${GITHUB_WORKSPACE}/kibot_outputs/.nojekyll
         find ${GITHUB_WORKSPACE}/kibot_outputs -type l -delete
          cat > ${GITHUB_WORKSPACE}/kibot_outputs/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Redirecting...</title>
              <meta http-equiv="refresh" content="0; url=navigate/creeper-navigate.html">
            </head>
            <body>
              <p>Redirecting to <a href="navigate/creeper-navigate.html">KiBot outputs</a>...</p>
            </body>
          </html>
          EOF


      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kibot-outputs
          path: |
            kibot_outputs

  deploy:
    runs-on: ubuntu-latest
    needs: kibot
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: kibot-outputs
          path: kibot_outputs

      - name: Upload to GH pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: kibot_outputs

      - name: Deploy to GH pages
        id: deployment
        uses: actions/deploy-pages@v4

